#!/bin/bash
# Posts to the metafridge from the shell.

metafridgeURL="http://metafridge.metalab.at"
metafridgeCGI="/cgi-bin/post_text.cgi"


USAGE="Usage: `basename $0` [-h][-s style] message
Available Styles:
    scrollnormal
    scrollfast
    scrolltoofast
    blinkslow
    blinkfast
    blinkstrobo
    scrollup
    scrolldown
    sinewave"

# Parse command line options.
while getopts hs: OPT; do
    case "$OPT" in
        h)
            echo Help: $USAGE
            exit 0
            ;;
        s)
            PASSEDSTYLE=$OPTARG
            case "$PASSEDSTYLE" in
                scrollnormal)
                    STYLE=1
                    ;;
                scrollfast)
                    STYLE=2
                    ;;
                scrolltoofast)
                    STYLE=3
                    ;;
                blinkslow)
                    STYLE=4
                    ;;
                blinkfast)
                    STYLE=5
                    ;;
                blinkstrobo)
                    STYLE=6
                    ;;
                scrollup)
                    STYLE=7
                    ;;
                scrollup)
                    STYLE=8
                    ;;
                sinewave)
                    STYLE=9
                    ;;
            esac
            ;;
        \?)
            # getopts issues an error message
            echo $USAGE >&2
            exit 1
            ;;
    esac
done

# Remove the switches we parsed above.
shift `expr $OPTIND - 1`

# We want at least one non-option argument. 
# Remove this block if you don't need it.
if [ $# -eq 0 ]; then
    echo $USAGE >&2
    exit 1
fi

# Access additional arguments as usual through 
# variables $@, $*, $1, $2, etc. or using this loop:
#for PARAM; do
#    echo $PARAM
#done

MESSAGE="$*"
echo "${metafridgeURL}${metafridgeCGI}" --data "lauftext=${MESSAGE}&playfunction=${STYLE}"
curl -v "${metafridgeURL}${metafridgeCGI}" --data-urlencode "lauftext=${MESSAGE}" --data "&playfunction=${STYLE}"

# EOF
