//font.h
/******************************************************************************
* METAFRIDGE FONT UTILS
******************************************************************************/

#include <avr/pgmspace.h>

#define FAST

#ifdef FAST
#define COUNTER_DELAY		1
#define SPACE_BETWEEN_CHARS	2
#else
#define COUNTER_DELAY		7
#define SPACE_BETWEEN_CHARS	1
#endif

#define MAX_CHAR_WIDTH		7
#define SPACE_CHAR_WIDTH	3

extern const uint8_t ascii_maps[][MAX_CHAR_WIDTH] PROGMEM;	// Actual data in ./font_maps/

void get_temp_ascii_map( uint8_t ascii_code );
uint16_t show_ascii_xy( uint8_t ascii_code, int16_t offset_x, int16_t offset_y );

#define I________	0x00
#define I_______x	0x01
#define I______x_	0x02
#define I______xx	0x03
#define I_____x__	0x04
#define I_____x_x	0x05
#define I_____xx_	0x06
#define I_____xxx	0x07
#define I____x___	0x08
#define I____x__x	0x09
#define I____x_x_	0x0A
#define I____x_xx	0x0B
#define I____xx__	0x0C
#define I____xx_x	0x0D
#define I____xxx_	0x0E
#define I____xxxx	0x0F
#define I___x____	0x10
#define I___x___x	0x11
#define I___x__x_	0x12
#define I___x__xx	0x13
#define I___x_x__	0x14
#define I___x_x_x	0x15
#define I___x_xx_	0x16
#define I___x_xxx	0x17
#define I___xx___	0x18
#define I___xx__x	0x19
#define I___xx_x_	0x1A
#define I___xx_xx	0x1B
#define I___xxx__	0x1C
#define I___xxx_x	0x1D
#define I___xxxx_	0x1E
#define I___xxxxx	0x1F
#define I__x_____	0x20
#define I__x____x	0x21
#define I__x___x_	0x22
#define I__x___xx	0x23
#define I__x__x__	0x24
#define I__x__x_x	0x25
#define I__x__xx_	0x26
#define I__x__xxx	0x27
#define I__x_x___	0x28
#define I__x_x__x	0x29
#define I__x_x_x_	0x2A
#define I__x_x_xx	0x2B
#define I__x_xx__	0x2C
#define I__x_xx_x	0x2D
#define I__x_xxx_	0x2E
#define I__x_xxxx	0x2F
#define I__xx____	0x30
#define I__xx___x	0x31
#define I__xx__x_	0x32
#define I__xx__xx	0x33
#define I__xx_x__	0x34
#define I__xx_x_x	0x35
#define I__xx_xx_	0x36
#define I__xx_xxx	0x37
#define I__xxx___	0x38
#define I__xxx__x	0x39
#define I__xxx_x_	0x3A
#define I__xxx_xx	0x3B
#define I__xxxx__	0x3C
#define I__xxxx_x	0x3D
#define I__xxxxx_	0x3E
#define I__xxxxxx	0x3F
#define I_x______	0x40
#define I_x_____x	0x41
#define I_x____x_	0x42
#define I_x____xx	0x43
#define I_x___x__	0x44
#define I_x___x_x	0x45
#define I_x___xx_	0x46
#define I_x___xxx	0x47
#define I_x__x___	0x48
#define I_x__x__x	0x49
#define I_x__x_x_	0x4A
#define I_x__x_xx	0x4B
#define I_x__xx__	0x4C
#define I_x__xx_x	0x4D
#define I_x__xxx_	0x4E
#define I_x__xxxx	0x4F
#define I_x_x____	0x50
#define I_x_x___x	0x51
#define I_x_x__x_	0x52
#define I_x_x__xx	0x53
#define I_x_x_x__	0x54
#define I_x_x_x_x	0x55
#define I_x_x_xx_	0x56
#define I_x_x_xxx	0x57
#define I_x_xx___	0x58
#define I_x_xx__x	0x59
#define I_x_xx_x_	0x5A
#define I_x_xx_xx	0x5B
#define I_x_xxx__	0x5C
#define I_x_xxx_x	0x5D
#define I_x_xxxx_	0x5E
#define I_x_xxxxx	0x5F
#define I_xx_____	0x60
#define I_xx____x	0x61
#define I_xx___x_	0x62
#define I_xx___xx	0x63
#define I_xx__x__	0x64
#define I_xx__x_x	0x65
#define I_xx__xx_	0x66
#define I_xx__xxx	0x67
#define I_xx_x___	0x68
#define I_xx_x__x	0x69
#define I_xx_x_x_	0x6A
#define I_xx_x_xx	0x6B
#define I_xx_xx__	0x6C
#define I_xx_xx_x	0x6D
#define I_xx_xxx_	0x6E
#define I_xx_xxxx	0x6F
#define I_xxx____	0x70
#define I_xxx___x	0x71
#define I_xxx__x_	0x72
#define I_xxx__xx	0x73
#define I_xxx_x__	0x74
#define I_xxx_x_x	0x75
#define I_xxx_xx_	0x76
#define I_xxx_xxx	0x77
#define I_xxxx___	0x78
#define I_xxxx__x	0x79
#define I_xxxx_x_	0x7A
#define I_xxxx_xx	0x7B
#define I_xxxxx__	0x7C
#define I_xxxxx_x	0x7D
#define I_xxxxxx_	0x7E
#define I_xxxxxxx	0x7F

#define Ix_______	0x80
#define Ix______x	0x81
#define Ix_____x_	0x82
#define Ix_____xx	0x83
#define Ix____x__	0x84
#define Ix____x_x	0x85
#define Ix____xx_	0x86
#define Ix____xxx	0x87
#define Ix___x___	0x88
#define Ix___x__x	0x89
#define Ix___x_x_	0x8A
#define Ix___x_xx	0x8B
#define Ix___xx__	0x8C
#define Ix___xx_x	0x8D
#define Ix___xxx_	0x8E
#define Ix___xxxx	0x8F
#define Ix__x____	0x90
#define Ix__x___x	0x91
#define Ix__x__x_	0x92
#define Ix__x__xx	0x93
#define Ix__x_x__	0x94
#define Ix__x_x_x	0x95
#define Ix__x_xx_	0x96
#define Ix__x_xxx	0x97
#define Ix__xx___	0x98
#define Ix__xx__x	0x99
#define Ix__xx_x_	0x9A
#define Ix__xx_xx	0x9B
#define Ix__xxx__	0x9C
#define Ix__xxx_x	0x9D
#define Ix__xxxx_	0x9E
#define Ix__xxxxx	0x9F
#define Ix_x_____	0xA0
#define Ix_x____x	0xA1
#define Ix_x___x_	0xA2
#define Ix_x___xx	0xA3
#define Ix_x__x__	0xA4
#define Ix_x__x_x	0xA5
#define Ix_x__xx_	0xA6
#define Ix_x__xxx	0xA7
#define Ix_x_x___	0xA8
#define Ix_x_x__x	0xA9
#define Ix_x_x_x_	0xAA
#define Ix_x_x_xx	0xAB
#define Ix_x_xx__	0xAC
#define Ix_x_xx_x	0xAD
#define Ix_x_xxx_	0xAE
#define Ix_x_xxxx	0xAF
#define Ix_xx____	0xB0
#define Ix_xx___x	0xB1
#define Ix_xx__x_	0xB2
#define Ix_xx__xx	0xB3
#define Ix_xx_x__	0xB4
#define Ix_xx_x_x	0xB5
#define Ix_xx_xx_	0xB6
#define Ix_xx_xxx	0xB7
#define Ix_xxx___	0xB8
#define Ix_xxx__x	0xB9
#define Ix_xxx_x_	0xBA
#define Ix_xxx_xx	0xBB
#define Ix_xxxx__	0xBC
#define Ix_xxxx_x	0xBD
#define Ix_xxxxx_	0xBE
#define Ix_xxxxxx	0xBF
#define Ixx______	0xC0
#define Ixx_____x	0xC1
#define Ixx____x_	0xC2
#define Ixx____xx	0xC3
#define Ixx___x__	0xC4
#define Ixx___x_x	0xC5
#define Ixx___xx_	0xC6
#define Ixx___xxx	0xC7
#define Ixx__x___	0xC8
#define Ixx__x__x	0xC9
#define Ixx__x_x_	0xCA
#define Ixx__x_xx	0xCB
#define Ixx__xx__	0xCC
#define Ixx__xx_x	0xCD
#define Ixx__xxx_	0xCE
#define Ixx__xxxx	0xCF
#define Ixx_x____	0xD0
#define Ixx_x___x	0xD1
#define Ixx_x__x_	0xD2
#define Ixx_x__xx	0xD3
#define Ixx_x_x__	0xD4
#define Ixx_x_x_x	0xD5
#define Ixx_x_xx_	0xD6
#define Ixx_x_xxx	0xD7
#define Ixx_xx___	0xD8
#define Ixx_xx__x	0xD9
#define Ixx_xx_x_	0xDA
#define Ixx_xx_xx	0xDB
#define Ixx_xxx__	0xDC
#define Ixx_xxx_x	0xDD
#define Ixx_xxxx_	0xDE
#define Ixx_xxxxx	0xDF
#define Ixxx_____	0xE0
#define Ixxx____x	0xE1
#define Ixxx___x_	0xE2
#define Ixxx___xx	0xE3
#define Ixxx__x__	0xE4
#define Ixxx__x_x	0xE5
#define Ixxx__xx_	0xE6
#define Ixxx__xxx	0xE7
#define Ixxx_x___	0xE8
#define Ixxx_x__x	0xE9
#define Ixxx_x_x_	0xEA
#define Ixxx_x_xx	0xEB
#define Ixxx_xx__	0xEC
#define Ixxx_xx_x	0xED
#define Ixxx_xxx_	0xEE
#define Ixxx_xxxx	0xEF
#define Ixxxx____	0xF0
#define Ixxxx___x	0xF1
#define Ixxxx__x_	0xF2
#define Ixxxx__xx	0xF3
#define Ixxxx_x__	0xF4
#define Ixxxx_x_x	0xF5
#define Ixxxx_xx_	0xF6
#define Ixxxx_xxx	0xF7
#define Ixxxxx___	0xF8
#define Ixxxxx__x	0xF9
#define Ixxxxx_x_	0xFA
#define Ixxxxx_xx	0xFB
#define Ixxxxxx__	0xFC
#define Ixxxxxx_x	0xFD
#define Ixxxxxxx_	0xFE
#define Ixxxxxxxx	0xFF

//EOF
